### ISSUE TITLE
Support piping into set

### ISSUE THREAD

**Issue by nodesocket** [nodesocket/jsonlite#14]
How to support piping into set?

```
echo "{}" | jsonlite set
```

**Comment by evuez** [comment]
A simple `while read...done` should work:

``` bash
function jsonlite_set {
    while read value; do
        echo "$value" | json_reformat > "$JSONLITE_PATH/$uuid"
    done;
}
echo '{"a": "b"}' | jsonlite_set
```

**Comment by nodesocket** [comment]
Seems like changing the `set` command to start with:

``` shell
local value="$1"

if [[ -z "$value" ]]; then
  while read -r piped; do
    value=$piped
  done;
fi

if [[ -z "$value" ]]; then
  echo "Missing required argument json document" 1>&2
  exit 4
fi
```

Seems to work. Can you think of a better way to write this?

**Comment by evuez** [comment]
The problem here is that (haven't tested it, correct me if I'm wrong) if you do something like `for i in $(seq 1 3); do echo '{"a": "b"}'; done | jsonlite set` you'll only get the last echo.
Also, with a `cat file.json | jsonlite set` you would get only the last line of the file in `$value`.
Maybe a better way would be to do `value+="$piped"` so that you store the whole file. But then you would get `{"a": "b"}{"a": "b"}{"a": "b"}` with the first example... I don't know what's best...

**Comment by nodesocket** [comment]
@evuez correct, it only get's the last iteration. Any ideas?

```
➜  jsonlite git:(master) ✗ for i in $(seq 1 3); do echo '{"a": "b"}'; done | jsonlite set
EC816848-F72E-440B-B42D-68C096198F9E
➜  jsonlite git:(master) ✗ jsonlite get EC816848-F72E-440B-B42D-68C096198F9E
{
    "a": "b"
}
```

**Comment by nodesocket** [comment]
I actually got something working:

``` shell
if [[ -z "$value" && ! -t 0 ]]; then
    while read -r piped; do
      value+=$piped
    done;
fi
```

The trick was using `+=` and also checking `! -t 0` which checks if we are piping.

**Comment by evuez** [comment]
That's nice, I didn't know about the `! -t 0`!
